### ISSUE TITLE
BK-02 Remover o uso de System.out.println

### ISSUE THREAD

**Issue by helciodasilva** [heltonanalista/bikeshop#3]
![image](https://github.com/heltonanalista/bikeshop/assets/12960457/61a20ea9-b9f6-44b1-95ba-00a2479310b8)

![image](https://github.com/heltonanalista/bikeshop/assets/12960457/16bf4597-de3d-4a4c-b345-6bfff67bf7b8)

**Comment by heltonanalista** [comment]
Resolvido #2
